import torch
import torch.nn as nn
from typing import Tuple, Dict, Optional
from torchvision import transforms
from transformers.image_transforms import center_to_corners_format

from sparrow.model.ddetr_sam2 import CustomDDETRSAM2Model


class DDETRProposalGenerator:
    """
    Thin wrapper around CustomDDETRSAM2Model that mirrors
    groma_sam2/eval/run_ddetr_sam2.py and keeps query embeddings aligned with
    checkpoint configuration.
    """

    def __init__(
        self,
        model_path: str,
        device: Optional[torch.device] = None,
    ):
        self.device = device if device is not None else torch.device("cuda" if torch.cuda.is_available() else "cpu")
        self.processor = transforms.Compose(
            [
                transforms.ToTensor(),
                transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
            ]
        )

        base_model = CustomDDETRSAM2Model.from_pretrained(model_path)
        self.model = self._align_model_with_checkpoint(base_model).to(self.device)
        self.model.eval()
        self.model.requires_grad_(False)
        self.hidden_dim = self.model.config.ddetr_cfg.d_model

    @staticmethod
    def _align_model_with_checkpoint(model: CustomDDETRSAM2Model) -> CustomDDETRSAM2Model:
        """
        Ensure the detector configuration is self-consistent: when two-stage
        refinement is enabled the number of decoder queries must match the number
        of proposals generated by the encoder branch.
        """
        cfg = model.config.ddetr_cfg
        desired_queries = cfg.two_stage_num_proposals if getattr(cfg, "two_stage", False) else cfg.num_queries

        cfg.num_queries = desired_queries
        transformer = model.ddetr_transformer
        transformer.config.num_queries = desired_queries
        transformer.config.two_stage_num_proposals = cfg.two_stage_num_proposals
        transformer.decoder.config.num_queries = desired_queries
        transformer.decoder.config.two_stage_num_proposals = cfg.two_stage_num_proposals

        old_weight = transformer.query_position_embeddings.weight.data
        if old_weight.shape[0] != desired_queries:
            new_embed = nn.Embedding(desired_queries, old_weight.shape[1])
            copy_len = min(old_weight.shape[0], desired_queries)
            with torch.no_grad():
                if copy_len > 0:
                    new_embed.weight[:copy_len] = old_weight[:copy_len]
                if desired_queries > copy_len:
                    nn.init.xavier_uniform_(new_embed.weight[copy_len:])
            transformer.query_position_embeddings = new_embed

        return model

    def generate_proposals(
        self,
        pil_image,
        topk: int,
        score_power: Tuple[float, float],
    ) -> Dict[str, torch.Tensor]:
        """
        Run the detector on a single PIL image and return top-k proposals with
        their embeddings and scores.
        """
        pixel_values = self.processor(pil_image).unsqueeze(0).to(self.device)

        with torch.inference_mode():
            outputs = self.model(images=pixel_values)

        pred_boxes = center_to_corners_format(outputs.pred_boxes)[0].to(self.device)

        logits_coco = outputs.logits["coco"].sigmoid()
        logits_sa1b = outputs.logits["sa1b"].sigmoid()
        scores_coco = logits_coco.max(dim=-1).values[0]
        scores_sa1b = logits_sa1b.max(dim=-1).values[0]

        alpha, beta = score_power
        combined_scores = torch.pow(scores_coco, alpha) * torch.pow(scores_sa1b, beta)

        num_props = combined_scores.numel()
        if num_props == 0:
            return {
                "boxes": torch.empty((0, 4), device=self.device),
                "features": torch.empty((0, self.hidden_dim), device=self.device),
                "scores": torch.empty((0,), device=self.device),
                "mask": torch.empty((0,), dtype=torch.bool, device=self.device),
            }

        topk = min(topk, num_props)
        top_scores, top_indices = combined_scores.topk(topk)
        boxes = pred_boxes[top_indices]
        features = outputs.last_hidden_state[0].to(self.device)[top_indices]
        mask = torch.ones_like(top_scores, dtype=torch.bool, device=self.device)

        return {
            "boxes": boxes,
            "features": features,
            "scores": top_scores,
            "mask": mask,
        }



# from PIL import Image, ImageDraw
# import torch

# def draw_ddetr_boxes_on_pil(
#     pil_image: Image.Image,
#     boxes: torch.Tensor,            # shape (N, 4) in (x0, y0, x1, y1)
#     scores: torch.Tensor | None = None,  # shape (N,) optional
#     mask: torch.Tensor | None = None,    # shape (N,) bool, optional
#     *,
#     normalized: bool = True,        # True if boxes are in [0,1] coords
#     color: tuple[int,int,int] = (255, 0, 0),
#     width: int = 3
# ) -> Image.Image:
#     """
#     Draw DDETR boxes on a PIL image.

#     - If `normalized=True`, scales boxes by image (W,H).
#     - If `mask` provided, filters boxes/scores accordingly.
#     - Clips boxes to image bounds.
#     """
#     img = pil_image.copy()
#     draw = ImageDraw.Draw(img)

#     if boxes.numel() == 0:
#         return img

#     if mask is not None:
#         boxes = boxes[mask]
#         if scores is not None:
#             scores = scores[mask]

#     boxes = boxes.detach().cpu().float()
#     W, H = img.size

#     if normalized:
#         scale = torch.tensor([W, H, W, H], dtype=boxes.dtype)
#         boxes = boxes * scale

#     # clip to image bounds
#     boxes[:, [0, 2]] = boxes[:, [0, 2]].clamp(0, W - 1)
#     boxes[:, [1, 3]] = boxes[:, [1, 3]].clamp(0, H - 1)

#     # draw
#     for i, b in enumerate(boxes):
#         x0, y0, x1, y1 = b.tolist()
#         draw.rectangle([x0, y0, x1, y1], outline=color, width=width)

#         if scores is not None:
#             s = float(scores[i])
#             txt = f"{s:.2f}"

#             # small text background box for readability (Pillow>=9: textbbox exists)
#             try:
#                 tb = draw.textbbox((x0, y0), txt)
#                 draw.rectangle(tb, fill=color)
#                 draw.text((x0, y0), txt, fill=(255, 255, 255))
#             except Exception:
#                 # fallback: just draw text
#                 draw.text((x0, y0), txt, fill=color)

#     return img


# img_vis = draw_ddetr_boxes_on_pil(
#     pil_image,
#     boxes=props["boxes"],         # already (x0,y0,x1,y1) but normalized
#     scores=props["scores"],
#     mask=props["mask"],
#     normalized=True,              # set False if your boxes are pixel coords
#     color=(0, 255, 0),
#     width=3
# )
# img_vis.show()  # or img_vis.save("vis.png")
